version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:16.2-alpine
    ports:
      - "5432:5432"
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: